@extends('layouts.public')

@section('title', $post->title . ' — Zforce Chronicles')

@section('content')
<article class="py-24">
    <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <!-- Header -->
        <header class="mb-12">
            <div class="flex items-center space-x-3 mb-6">
                <a href="{{ route('chronicles') }}" class="text-xs font-mono text-vortex-400 hover:text-vortex-300 transition-colors">← BACK TO CHRONICLES</a>
            </div>
            
            <div class="flex items-center space-x-3 mb-4">
                <span class="px-2 py-1 bg-vortex-500/20 text-vortex-300 text-xs font-mono rounded">{{ $post->category }}</span>
                <span class="text-slate-600 text-xs font-mono">{{ $post->published_at?->format('F j, Y') }}</span>
                <span class="text-slate-600 text-xs font-mono">{{ $post->view_count }} views</span>
            </div>
            
            <h1 class="text-3xl md:text-4xl font-bold text-white mb-4">{{ $post->title }}</h1>
            
            <div class="flex items-center space-x-3">
                <div class="w-8 h-8 bg-vortex-600 rounded-full flex items-center justify-center">
                    <span class="text-xs font-mono text-white">{{ strtoupper(substr($post->author_name, 0, 1)) }}</span>
                </div>
                <div>
                    <div class="text-sm text-white font-medium">{{ $post->author_name }}</div>
                    <div class="text-xs text-slate-600 font-mono">Temporal Archivist</div>
                </div>
            </div>
        </header>
        
        <!-- Content -->
        <div class="prose prose-invert prose-lg max-w-none">
            {!! nl2br(e($post->content)) !!}
        </div>
        
        <!-- Footer -->
        <footer class="mt-12 pt-8 border-t border-vortex-600/20">
            <div class="flex items-center justify-between">
                <div class="text-xs text-slate-600 font-mono">
                    @if($post->generating_model)
                    Generated by: {{ $post->generating_model }}
                    @endif
                </div>
                <div class="text-xs text-slate-600 font-mono">
                    Temporal ID: {{ $post->slug }}
                </div>
            </div>
        </footer>
        
        <!-- Related -->
        @if($related->isNotEmpty())
        <div class="mt-16">
            <h3 class="text-lg font-semibold text-white mb-6 font-mono">Related Chronicles</h3>
            <div class="space-y-4">
                @foreach($related as $rel)
                <a href="{{ route('chronicle.show', $rel->slug) }}" class="block bg-vortex-800/30 border border-vortex-600/20 rounded-lg p-4 hover:border-vortex-400/30 transition-all">
                    <h4 class="text-sm font-semibold text-white hover:text-vortex-300 transition-colors">{{ $rel->title }}</h4>
                    <p class="text-xs text-slate-500 mt-1">{{ Str::limit($rel->excerpt, 100) }}</p>
                </a>
                @endforeach
            </div>
        </div>
        @endif
    </div>
</article>
@endsection
